# Generated by Django 4.2.1 on 2023-05-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('created_at', models.DateField(auto_now=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('decision', models.CharField(max_length=500)),
            ],
        ),
    ]
